name: Java CI

on:
  push:
    branches:
    - Test2
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 16
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Archive artifacts (artifacts)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Galactifun
        path: target/Galactifun vMODIFIED.jar
